### PR TITLE
backport trust's faster-deploy branch

### PR DESCRIPTION
**Pull request by japaric**
cf. japaric/trust#24

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2e8a53a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2e8a53a with merge 2e8a53a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.115), [status-travis](https://travis-ci.org/japaric/xargo/builds/168088514)
Approved by: japaric
Pushing 2e8a53a7841039c32a7bee260a765c508cce611b to master...

**Pull request merged**
