### PR TITLE
revamp the CI infrastructure

### LINKED ISSUE #52: No binary releases for Windows since v0.1.8
It seems that new tags are not being picked up by AppVeyor.

### LINKED ISSUE #61: Build the binary releases using LTO

### PR DESCRIPTION
**Pull request by japaric**
closes #52
closes #61

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 190c81b with merge 190c81b...

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 27e9181 with merge 27e9181...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/167811367)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit d6cc6f3 with merge d6cc6f3...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit afb2b4f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit afb2b4f with merge afb2b4f...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5c03bd3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5c03bd3 with merge 5c03bd3...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.101)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.102), [status-travis](https://travis-ci.org/japaric/xargo/builds/167819323)
Approved by: japaric
Pushing 5c03bd309aae9d11536ccc9923db9aab7cbe3ef0 to master...

**Pull request merged**
