### PR TITLE
fix for latest rustc

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes xargo for https://github.com/rust-lang/rust/pull/63637

### CODE REVIEW

**Comment by RalfJung** [comment]
Cycling PR to get CI with latest nightly including the breaking changes.

**Comment by RalfJung** [comment]
bors try

**Comment by RalfJung** [comment]
@jethrogb any chance you could review this? This blocks fixing Miri.

If that's okay for you, I could also do such fixes on my own in the future. I'd need owner access to xargo on crates.io, though.

**Comment by LukasKalbertodt** [comment]
Will this be released to crates.io?
Thanks for your work!

**Comment by RalfJung** [comment]
@jethrogb if you give me crates.io permissions I can do the release. Whatever you prefer.

**Comment by RalfJung** [comment]
@jethrogb is 8d1cd7c8811aebe4211c5855e69d8a65a4db6f41 the commit you used for 0.3.15? It does not seem to have a tag, or you forgot to push it.

**Pull request merged**
