### PR TITLE
nicer errors messages

### PR DESCRIPTION
**Pull request by japaric**
print them using Display not Debug

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fad1a60 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fad1a60 with merge fad1a60...

**Comment by japaric** [comment]
@homunkulus retry

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 35bef88 has been approved by `japaric`

**Pull request closed without merging**
