### PR TITLE
unbreak the cache

### LINKED ISSUE #67: travis: caching appears to not work
```
attempting to download cache archive

fetching v0.2.0-rc1/cache-linux-trusty-e98a5aab280b2cf9177d6093bcf0d8ec968d424ea3df937fa3cf9b5ed4aee1a3.tgz

fetching master/cache-linux-trusty-e98a5aab280b2cf9177d6093bcf0d8ec968d424ea3df937fa3cf9b5ed4aee1a3.tgz

could not download cache
```

### PR DESCRIPTION
**Pull request by japaric**
closes #67

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 1306279 with merge 1306279...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f4ef126 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f4ef126 with merge f4ef126...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a2d0f44 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a2d0f44 with merge a2d0f44...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f9bbd7d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f9bbd7d with merge f9bbd7d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.113), [status-travis](https://travis-ci.org/japaric/xargo/builds/168065475)
Approved by: japaric
Pushing f9bbd7d0912d89f45083307d8794ab3101b1f62d to master...

**Pull request merged**
