### PR TITLE
don't rebuild the sysroot if profile.*.lto changed in Cargo.toml

### PR DESCRIPTION
**Pull request by japaric**
cc #79

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 66fc18c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 66fc18c with merge 66fc18c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.128)

**Pull request merged**
