### PR TITLE
Fix for latest nightly: need to add a patch section

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/japaric/xargo/issues/227

### CODE REVIEW

**Comment by jethrogb** [comment]
Anyway, this (and #229) don't work (fully). It works if you're using only the `rust-src` component or `XARGO_RUST_SRC`. However, if you're specifying the source in `Xargo.toml`, the dependency on `rustc-std-workspace-core` will point to the wrong `libcore` source.

I've come up with 3 different approaches to fix this, not sure which one is best:

1. If there is a `std` crate in the blueprint, compute `../tools/rustc-std-workspace-core` from that path (or use the same git) and use that as the `[patch]`.

2. If there is a `std` crate in the blueprint, find the spec of the core dependency, then generate a `rustc-std-workspace-core` crate in the tempdir with that core (how would this work if `std` is a git dependency?). Then, use that temp crate as the `[patch]`.

3. Use the logic in this PR or #229 to generate the `[patch]` by default. Let users specify their own `[patch]`es in `Xargo.toml`

**Comment by RalfJung** [comment]
I don't have a strong opinion about solving this problem.

However, I think we can merge one of #228 and #229 to fix the immediate problem for everyone using an unchanged libstd/`XARGO_RUST_SRC`, and then separately have an issue for fixing the other case?

**Comment by jethrogb** [comment]
I think this PR doesn't work for compiling `core` without `Xargo.toml` so I'd vote #229

**Comment by RalfJung** [comment]
> I think this PR doesn't work for compiling core without Xargo.toml so I'd vote

Not sure hat you mean by that, but fine for me.

However, please make sure xargo still works for old libstd that does not have `rustc-std-workspace-core` yet.

**Comment by RalfJung** [comment]
Also I did the proper thing for fixing the deprecation warnings instead of just silencing them, feel free to copy those parts of my patches.

**Comment by RalfJung** [comment]
Can't you check whether the rustc-std-workspace-core folder exists? That's what this patch does.

**Comment by jethrogb** [comment]
How would that work for a git source? Xargo doesn't have access to the source.

**Comment by RalfJung** [comment]
I'm afraid I am not familiar with the mode of operation of xargo you are referring to. I have only ever used xargo with the `rust-src` component, and I think it is reasonable to keep xargo compatible with older Rust nightlies -- it's not much effort.

**Comment by japaric** [comment]
Thanks for the PRs, @RalfJung and @jethrogb! I'm going to land this one since it works with older nightly releases. On that note: @RalfJung, could you add a new builder that runs the test suite on an older nightly? I think the change should boil down to adding these lines to .travis.yml:

``` yaml
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly-2018-12-XX
```

Feel free to land this with that change.

bors delegate+

**Comment by japaric** [comment]
Hmm, I think you'll have to add `master` to the list of branches in .travis.yml.

I'll kick off a try build for now.

bors try

**Comment by japaric** [comment]
Link to try build: https://travis-ci.org/japaric/xargo/builds/468425445

**Comment by RalfJung** [comment]
Looks like CI is not in a good state...
```
E: Unable to locate package gcc-arm-none-eabi
```

**Comment by RalfJung** [comment]
`ci/script.sh` does nothing if the branch is "master"... seems like this is not intended to work for PRs.  Odd.

bors try

**Comment by RalfJung** [comment]
```
  failed to read `/home/travis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcompiler_builtins/Cargo.toml`
```
Well indeed, that file does not exist.

**Comment by bjorn3** [comment]
@RalfJung `compiler_builtins` is one of those crates moved to crates.io.

**Comment by RalfJung** [comment]
Ah then probably the testcases are wrong now.

**Comment by RalfJung** [comment]
bors try

**Comment by RalfJung** [comment]
Why is it not listening now?^^

bors try

**Comment by RalfJung** [comment]
Oh it did listen, just GH didn't update. Never mind.

**Comment by RalfJung** [comment]
Well that looks really green to me!

bors r+

**Comment by RalfJung** [comment]
Uh, no, just the nightly-XXX didn't run the tests because it's not exactly "nightly".

bors r-

**Comment by RalfJung** [comment]
bors try

**Comment by RalfJung** [comment]
Okay, now it actually tested something and the tests come back green. :)

**Comment by thepowersgang** [comment]
When would we expect to see this change in a released version on crates.io?

**Pull request merged**
