### PR TITLE
.travis: remove webhooks

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f154b71 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f154b71 with merge f154b71...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.130)

**Pull request merged**
