### PR TITLE
update the README

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4b8da1d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4b8da1d with merge 4b8da1d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/236220014?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
Network error

@homunkulus retry

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e36e85f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e36e85f with merge 5eadcda...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.186), [status-travis](https://travis-ci.org/japaric/xargo/builds/236518399?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 5eadcda66214db1026a9a785f4d37ca8a9c451a9 to master...

**Pull request merged**
