### PR TITLE
fixed typo in readme

### PR DESCRIPTION
**Pull request by anickol**
There is a typo in the readme.

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks. :)

**Comment by RalfJung** [comment]
Looks like CI is failing. That is certainly unrelated but GitHub won't let me merge this PR until CI is green... sorry. :/

We can leave this PR open, maybe someone finds the time to fix our CI (or maybe I do, but that could take a while).

**Comment by anickol** [comment]
I will take a look at the nightly build too.

**Comment by RalfJung** [comment]
Instead of adding a merge commit, could you please rebase on top of current master?

**Comment by anickol** [comment]
did it

**Comment by RalfJung** [comment]
Thanks. :)
bors r+

**Pull request merged**
