### PR TITLE
improve error message when the `rust-src` component is missing

### LINKED ISSUE #124: Better error message when `rust-src` is missing
When installing `xargo` without `rust-src`, there is no notification that `rust-src` is necessary.

Instead this opaque error is shown:

```
➜  05-led-roulette git:(master) xargo build --target thumbv7em-none-eabihf
error: couldn't walk the sysroot
caused by: IO error for operation on /home/james/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src: No such file or directory (os error 2)
caused by: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` for a backtrace
```

You actually provide the helpful solution here: https://github.com/japaric/xargo/blob/c428cf1f3096f6832f8f0fc8ef337fa73454934a/src/rustc.rs#L90, however this isn't printed (I'm not familiar with how `chain_err` works/should work).

It would be nice to also show that same error message when the error condition is triggered  on line 74.

### PR DESCRIPTION
**Pull request by japaric**
now you get:

```
$ xargo build
error: `rust-src` component not found. Run `rustup component add rust-src`.
note: run with `RUST_BACKTRACE=1` for a backtrace
```

closes #124

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5624cc6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5624cc6 with merge 5624cc6...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/231899999?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0e40c8c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0e40c8c with merge 0e40c8c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/231908533?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fd3225c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fd3225c with merge fd3225c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.182), [status-travis](https://travis-ci.org/japaric/xargo/builds/231910364?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing fd3225c82ec1c6d184c27ba5532ad8ea414fe305 to master...

**Pull request merged**
