### PR TITLE
stop using hardlinks

### LINKED ISSUE #30: weird error with cross-device hardlink
I'm using xargo within a docker container, where CARGO_HOME and ```~/.xargo``` are on different file systems.

This leads to the following error:

```
 Downloading https://static.rust-lang.org/dist/2016-08-10/rustc-nightly-src.tar.gz

[snipped out successful compiles]

     Running `rustc /data/riotbuild/.xargo/src/libcollections/lib.rs --crate-name collections --crate-type lib -C opt-level=3 -C metadata=f4d6828fe1f117b1 --out-dir /tmp/xargo.K94mJ2X6F8BN/target/cortex-m0plus/release/deps --emit=dep-info,link --target cortex-m0plus -L dependency=/tmp/xargo.K94mJ2X6F8BN/target/cortex-m0plus/release/deps --extern alloc=/tmp/xargo.K94mJ2X6F8BN/target/cortex-m0plus/release/deps/liballoc.rlib --extern rustc_unicode=/tmp/xargo.K94mJ2X6F8BN/target/cortex-m0plus/release/deps/librustc_unicode.rlib --extern core=/tmp/xargo.K94mJ2X6F8BN/target/cortex-m0plus/release/deps/libcore.rlib`
    Finished release [optimized] target(s) in 44.51 secs
error: Invalid cross-device link (os error 18)
```

Interestingly, just repeating the build command succeds.

This are the relevant strace parts:

```
[snip]

570   stat("/opt/rust/cargo/bin/xargo", {st_mode=S_IFREG|0775, st_size=2039944, ...}) = 0
570   clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9ee1c679d0) = 571
570   wait4(-1,  <unfinished ...>
571   execve("/opt/rust/cargo/bin/xargo", ["xargo", "build", "--target", "cortex-m0plus", "--verbose"], [/* 99 vars */]) = 0
[snip]
606   execve("/opt/rust/cargo/bin/rustc", ["rustc", "--print", "sysroot"], [/* 99 vars */] <unfinished ...>
[snip]
606   <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 607
606   --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=607, si_uid=1000, si_status=0, si_utime=2, si_stime=0} ---
606   sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
606   munmap(0x7fa5ff306000, 8192)      = 0
606   exit_group(0)                     = ?
606   +++ exited with 0 +++
571   <... select resumed> )            = 2 (in [6 8])
571   --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=606, si_uid=1000, si_status=0, si_utime=2, si_stime=0} ---
571   read(6, "", 64)                   = 0
571   fcntl(8, F_GETFL)                 = 0x800 (flags O_RDONLY|O_NONBLOCK)
571   fcntl(8, F_SETFL, O_RDONLY)       = 0
571   read(8, "", 16)                   = 0
571   close(8)                          = 0
571   close(6)                          = 0
571   wait4(606, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 606
571   open("/opt/rust/multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
571   fstat(5, {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
571   getdents(5, /* 55 entries */, 32768) = 2624
571   link("/opt/rust/multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-c8005792.so", "/data/riotbuild/.xargo/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-c8005792.so") = -1 EXDEV (Invalid cross-device link)
571   close(5)                          = 0
571   flock(4, LOCK_UN)                 = 0
571   close(4)                          = 0
571   flock(3, LOCK_UN)                 = 0
571   close(3)                          = 0
571   write(2, "\33(B\33[m", 6)         = 6
571   write(2, "\33[31m", 5)            = 5
571   write(2, "\33[1m", 4)             = 4
571   write(2, "error:", 6)             = 6
571   write(2, "\33(B\33[m", 6)         = 6
571   write(2, " ", 1)                  = 1
571   write(2, "Invalid cross-device link (os er"..., 39) = 39
571   write(2, "\n", 1)                 = 1
571   sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
571   munmap(0x7fdda8bca000, 8192)      = 0
571   exit_group(101)                   = ?
571   +++ exited with 101 +++
```

The only place where xargo hardlinks is in ```symlink_host_crates()```.

Maybe an option to actually symlink would be nice?

### PR DESCRIPTION
**Pull request by japaric**
closes #30

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f443cba has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f443cba with merge f443cba...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.85)
Approved by: japaric
Pushing f443cba998b2da4c65fe920f070ed5ab0bbcc569 to master...

**Pull request merged**
