### PR TITLE
cache Cargo artifacts

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a020866 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a020866 with merge a020866...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/165696591)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5b46164 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5b46164 with merge 5b46164...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2b7021a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2b7021a with merge 2b7021a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/165700758)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 07f0b0d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 07f0b0d with merge 07f0b0d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/165703592)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1572c88 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1572c88 with merge 1572c88...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.94), [status-travis](https://travis-ci.org/japaric/xargo/builds/165703929)
Approved by: japaric
Pushing 1572c88eb77ed3c2c19541c76d7b791d4e4e8fcb to master...

**Pull request merged**
