### PR TITLE
some clippy warnings fixed

### PR DESCRIPTION
**Pull request by 4tm4j33tk4ur**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+
Thank you!

**Comment by homunkulus** [comment]
:pushpin: Commit 9c78337 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9c78337 with merge 9c78337...

**Comment by japaric** [comment]
The tests passed but homu got stuck so I'm going to merge this manually.

Thanks again, @4tm4j33tk4ur and sorry for the delay!

**Pull request merged**
