### PR TITLE
windows extra files: support both old and new locations

### PR DESCRIPTION
**Pull request by RalfJung**
@Selyatin  can you test if this fixes https://github.com/japaric/xargo/issues/313?

### CODE REVIEW

**Comment by Selyatin** [comment]
Nope, I've cloned the repo's "win" branch and compiled it, then moved the binaries both xargo and xargo-check to /usr/local/bin and then I've tried to compile the project using "xargo build --target x86_64-pc-windows-gnu --release" and it gave me

```
error: couldn't copy /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/self-contained/crt2.o to /home/user/.xargo/lib/rustlib/x86_64-pc-windows-gnu/lib/self-contained/crt2.o
```

**Comment by RalfJung** [comment]
That file exists for me though when I install the "x86_64-pc-windows-gnu" target.
What does
```
ls /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib
```
say?

**Comment by RalfJung** [comment]
@Selyatin I think I found the problem; I forgot to also create the directory in the target. It should be fixed now.

Locally I now get this output:
```
$ xargo build --target x86_64-pc-windows-gnu --release
   Compiling compiler_builtins v0.1.39
   Compiling core v0.0.0 (/home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling libc v0.2.93
   Compiling cc v1.0.60
   Compiling std v0.0.0 (/home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std)
   Compiling unwind v0.0.0 (/home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/unwind)
   Compiling rustc-std-workspace-core v1.99.0 (/home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc)
   Compiling cfg-if v0.1.10
   Compiling adler v0.2.3
   Compiling rustc-demangle v0.1.18
   Compiling rustc-std-workspace-alloc v1.99.0 (/home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-alloc)
   Compiling panic_unwind v0.0.0 (/home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_unwind)
   Compiling panic_abort v0.0.0 (/home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_abort)
   Compiling gimli v0.23.0
   Compiling object v0.22.0
   Compiling std_detect v0.1.5 (/home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/stdarch/crates/std_detect)
   Compiling hashbrown v0.11.0
   Compiling miniz_oxide v0.4.0
   Compiling addr2line v0.14.0
error: linker `x86_64-w64-mingw32-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `std`
```
The error is expected since I don't have a linker for that toolchain installed.

**Comment by Selyatin** [comment]
Works! Thank you for your help!

**Pull request merged**
