### PR TITLE
refactor: drop serde dependency

### PR DESCRIPTION
**Pull request by japaric**
use rustc-cfg instead

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4defb90 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4defb90 with merge 4defb90...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.84)
Approved by: japaric
Pushing 4defb90536f99150e90b37009ad4a710be7aa5e1 to master...

**Pull request merged**
