### PR TITLE
nicer errors messages

### PR DESCRIPTION
**Pull request by japaric**
print them using Display not Debug

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 35bef88 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 35bef88 with merge e78d30c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.121), [status-travis](https://travis-ci.org/japaric/xargo/builds/169348799)
Approved by: japaric
Pushing e78d30c7689890473096f3de0c0688c6f69563b2 to master...

**Pull request merged**
