### PR TITLE
fix tests, target specifications now need a linker-flavor field

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e2a57eb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e2a57eb with merge e2a57eb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.178), [status-travis](https://travis-ci.org/japaric/xargo/builds/224091817)
Approved by: japaric
Pushing e2a57eb2fab2ea35f8de11b9dcdcc72ea95cc71e to master...

**Pull request merged**
