### PR TITLE
Fix warning about SipHasher being deprecated.

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 486524e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 486524e with merge 486524e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.144), [status-travis](https://travis-ci.org/japaric/xargo/builds/186791945)
Approved by: japaric
Pushing 486524eae1b9632ed29ec186e748188aeafe66a0 to master...

**Pull request merged**
