### PR TITLE
support the dev channel

### PR DESCRIPTION
**Pull request by japaric**
the path to the Rust source code must be specified via the
XARGO_RUST_SRC env variable.

cc @oli-obk

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fe08976 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fe08976 with merge fe08976...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/185055913)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6b6d189 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus retry

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bangbang: Invalid head SHA found, retrying: `0000000000000000000000000000000000000000`

**Comment by homunkulus** [comment]
:pushpin: Commit fe08976 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fe08976 with merge 239c969...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.138), [status-travis](https://travis-ci.org/japaric/xargo/builds/185067719)
Approved by: japaric
Pushing 239c96936f8d9d95a5b6862e654d4939cecf846b to master...

**Pull request merged**
