### PR TITLE
Fix linking for pc-windows-gnu targets

### PR DESCRIPTION
**Pull request by rkarp**
When linking `std.dll` and the other output executables for `windows-gnu` targets, the linker will complain that various object files are missing. They seem to be necessary only for `windows-gnu`, see also [this function](https://github.com/rust-lang/rust/blob/19e63bd50eb756e35416d7a8f01e2d63f419b373/src/bootstrap/compile.rs#L272).

Tested on Windows 7 64 bit.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks @rkarp.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 120f0f5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 120f0f5ec4287c7f6e38cb19ba48640f7fe07f55 with merge bb9dcb8c75abf6a42d53d69bd9b36b4d068923e1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.204), [status-travis](https://travis-ci.org/japaric/xargo/builds/301001510?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing bb9dcb8c75abf6a42d53d69bd9b36b4d068923e1 to master...

**Pull request merged**
