### PR TITLE
fix deploys

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit a6bb42a with merge a6bb42a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/187629867)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 1757cf1 with merge 1757cf1...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a5775e0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a5775e0 with merge a5775e0...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7944ec5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7944ec5 with merge 7944ec5...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/187813364)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a0dfd1d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a0dfd1d with merge a0dfd1d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.159), [status-travis](https://travis-ci.org/japaric/xargo/builds/187824946)
Approved by: japaric
Pushing a0dfd1dca513309e4d02737d7cd4fa0d82e1d772 to master...

**Pull request merged**
