### PR TITLE
don't add a weird " ( )" to `xargo -V` if not building from a git repo

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 87e1959 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 87e1959 with merge 87e1959...

**Comment by japaric** [comment]
@homunkulus retry force clean

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit abde233 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3dcec73 has been approved by `japaric`

**Pull request closed without merging**
