### PR TITLE
use recent nightly for macOS

### PR DESCRIPTION
**Pull request by japaric**
let's see if clearing the cache fixes the problem reported in rust-lang/cargo#4699

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 66cce2b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 66cce2b89a1343ca21e633237d62a8282cca5683 with merge f5d02ee0f4a36275da8335364129b7fdbbe76e49...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.203), [status-travis](https://travis-ci.org/japaric/xargo/builds/297305311?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing f5d02ee0f4a36275da8335364129b7fdbbe76e49 to master...

**Pull request merged**
