### PR TITLE
rustfmt and s/try!/?/g

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f3c660a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f3c660a with merge f3c660a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/186542601)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7e2285b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7e2285b with merge 7e2285b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.143), [status-travis](https://travis-ci.org/japaric/xargo/builds/186692980)
Approved by: japaric
Pushing 7e2285b6286ef323293ba7982cd84373fb8a1be5 to master...

**Pull request merged**
