### PR TITLE
Travis: propagate failures

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7491891 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7491891 with merge 7491891...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.116)

**Pull request merged**
