### PR TITLE
v2: drop a bunch of dependencies

### PR DESCRIPTION
**Pull request by japaric**
Xargo now depends on the rust-src component, which can be installed via
rustup

### CODE REVIEW

**Comment by japaric** [comment]
I don't think this will pass homu tests because rust-src is not installed (there's no rustup in the testing environment) but still ...

@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 86bfafd with merge 86bfafd...

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 3d5f985 with merge 3d5f985...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.104)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 0bd2f79 with merge 0bd2f79...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.105)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 338e8c3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 338e8c3 with merge 338e8c3...

**Comment by japaric** [comment]
@homunkulus r-

Have to remove the DEBUG commit first

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7c87d6e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7c87d6e with merge 7c87d6e...

**Comment by japaric** [comment]
Test passed.

**Pull request merged**
