### PR TITLE
print RUSTFLAGS in verbose mode

### PR DESCRIPTION
**Pull request by RalfJung**
It took me a little while to realize that xargo does add some flags on its own here. Having this output would have helped :)

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

@RalfJung, thanks for the PR.

**Comment by homunkulus** [comment]
:pushpin: Commit aaffb51 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aaffb51 with merge aaffb51...

**Comment by homunkulus** [comment]
:boom: Test timed out

**Comment by RalfJung** [comment]
That's not caused by this PR, is it?

**Comment by japaric** [comment]
@RalfJung nah, all tests are green. Homu is probably just having a bad day ...

Merging manually.

**Pull request merged**
