### PR TITLE
reject `--target foo.json`; suggest `--target foo`

### PR DESCRIPTION
**Pull request by japaric**
see #44 and rust-lang/rust#24666

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 93e6d57 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 93e6d57 with merge 93e6d57...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.188), [status-travis](https://travis-ci.org/japaric/xargo/builds/237748599?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 93e6d57bb266a190c76eb05636e8aa64480462fc to master...

**Pull request merged**
