### PR TITLE
tweak CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 29103f9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 29103f9 with merge 29103f9...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0ed6841 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0ed6841 with merge 0ed6841...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.141), [status-travis](https://travis-ci.org/japaric/xargo/builds/185780427)
Approved by: japaric
Pushing 0ed6841afa07331e1c154dceef36fd7ab6351ec2 to master...

**Pull request merged**
