### PR TITLE
fix warning

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 41b94ae has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 41b94ae with merge 41b94ae...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.190)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b67abf8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b67abf8 with merge b67abf8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.191), [status-travis](https://travis-ci.org/japaric/xargo/builds/261165015?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing b67abf8c1ad5e129618117715a10acf8aacadf6d to master...

**Pull request merged**
