### PR TITLE
CI: make sure the lockfile is up-to-date

### PR DESCRIPTION
**Pull request by RalfJung**
@jethrogb This seems like a useful thing to do on CI?

### CODE REVIEW

**Comment by RalfJung** [comment]
This is odd, CI should have failed because the lockfile actually isn't up-to-date...

**Comment by jethrogb** [comment]
Are you sure `--locked` works properly when the only changes are not related to dependencies? There's also `--frozen` but I never know the difference.

**Comment by RalfJung** [comment]
A `cargo build --locked` locally failed when I prepared this PR.

But maybe `cross` breaks `--locked`?

**Comment by RalfJung** [comment]
Turns out that yes, [this is a `cross` issue](https://github.com/rust-embedded/cross/issues/346) and they are [working on it](https://github.com/rust-embedded/cross/pull/348).

Meanwhile, no reason not to land this here so that we get the fix once `cross` is fixed  -- @jethrogb what do you think?

**Comment by RalfJung** [comment]
> There's also --frozen but I never know the difference.

`--frozen` implies `--locked`, but also refuses to download new crates into cargo's cache (it's basically "offline mode").

**Comment by RalfJung** [comment]
The `cross` issue is fixed; I will land this here.

bors r+

**Pull request merged**
