### PR TITLE
set RUST_TARGET_PATH when compiling the sysroot

### LINKED ISSUE #186: can't find target file on nightlies >= 2017-12-24
Beginning with `rustc 1.24.0-nightly (c284f8807 2017-12-24)`, `xargo` fails to build a project with a custom target with the following error message:

```bash
$ rustup default nightly-2017-12-25
info: using existing install for 'nightly-2017-12-25-x86_64-apple-darwin'
info: default toolchain set to 'nightly-2017-12-25-x86_64-apple-darwin'

  nightly-2017-12-25-x86_64-apple-darwin unchanged - rustc 1.24.0-nightly (c284f8807 2017-12-24)

$ xargo build --target=aarch64-none-elf -vv
+ "rustc" "--print" "sysroot"
+ "rustc" "--print" "target-list"
+ "cargo" "build" "--release" "--manifest-path" "/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.hHc88THUWAuQ/Cargo.toml" "--target" "aarch64-none-elf" "-v" "-p" "core"
   Compiling core v0.0.0 (file://$home/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore)
     Running `rustc --crate-name core $home/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=791964f4b0694a43 -C extra-filename=-791964f4b0694a43 --out-dir /var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.hHc88THUWAuQ/target/aarch64-none-elf/release/deps --target aarch64-none-elf -L dependency=/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.hHc88THUWAuQ/target/aarch64-none-elf/release/deps -L dependency=/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.hHc88THUWAuQ/target/release/deps --sysroot $home/.xargo -Z force-unstable-if-unmarked`
error: Error loading target specification: Could not find specification for target "aarch64-none-elf"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Could not compile `core`.
```

The same under older nightlies works just fine:

```bash
$ rustup default nightly-2017-12-24
info: using existing install for 'nightly-2017-12-24-x86_64-apple-darwin'
info: default toolchain set to 'nightly-2017-12-24-x86_64-apple-darwin'

  nightly-2017-12-24-x86_64-apple-darwin unchanged - rustc 1.24.0-nightly (169929308 2017-12-23)

$ xargo build --target=aarch64-none-elf -vv
+ "rustc" "--print" "sysroot"
+ "rustc" "--print" "target-list"
+ "cargo" "build" "--release" "--manifest-path" "/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.caIWJHjqBsOB/Cargo.toml" "--target" "aarch64-none-elf" "-v" "-p" "core"
   Compiling core v0.0.0 (file://$home/.rustup/toolchains/nightly-2017-12-24-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore)
     Running `rustc --crate-name core $home/.rustup/toolchains/nightly-2017-12-24-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=c366a2fc929ae3de -C extra-filename=-c366a2fc929ae3de --out-dir /var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.caIWJHjqBsOB/target/aarch64-none-elf/release/deps --target aarch64-none-elf -L dependency=/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.caIWJHjqBsOB/target/aarch64-none-elf/release/deps -L dependency=/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.caIWJHjqBsOB/target/release/deps --sysroot $home/.xargo -Z force-unstable-if-unmarked`
    Finished release [optimized + debuginfo] target(s) in 25.38 secs
+ "cargo" "build" "--release" "--manifest-path" "/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.XOsFBtvV9YKQ/Cargo.toml" "--target" "aarch64-none-elf" "-v" "-p" "compiler_builtins"
   Compiling compiler_builtins v0.1.0 (file://$home/.rustup/toolchains/nightly-2017-12-24-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcompiler_builtins)
     Running `rustc --crate-name build_script_build $home/.rustup/toolchains/nightly-2017-12-24-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcompiler_builtins/build.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg 'feature="compiler-builtins"' --cfg 'feature="default"' -C metadata=6c835e3701061413 -C extra-filename=-6c835e3701061413 --out-dir /var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.XOsFBtvV9YKQ/target/release/build/compiler_builtins-6c835e3701061413 -L dependency=/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.XOsFBtvV9YKQ/target/release/deps`
     Running `/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.XOsFBtvV9YKQ/target/release/build/compiler_builtins-6c835e3701061413/build-script-build`
     Running `rustc --crate-name compiler_builtins $home/.rustup/toolchains/nightly-2017-12-24-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcompiler_builtins/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="compiler-builtins"' --cfg 'feature="default"' -C metadata=47183b80144344d9 -C extra-filename=-47183b80144344d9 --out-dir /var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.XOsFBtvV9YKQ/target/aarch64-none-elf/release/deps --target aarch64-none-elf -L dependency=/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.XOsFBtvV9YKQ/target/aarch64-none-elf/release/deps -L dependency=/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/xargo.XOsFBtvV9YKQ/target/release/deps --sysroot $home/.xargo -Z force-unstable-if-unmarked`
    Finished release [optimized + debuginfo] target(s) in 3.34 secs
+ "cargo" "build" "--target=aarch64-none-elf" "-vv"
   Compiling rlibc v1.0.0
     Running `rustc --crate-name rlibc $home/.cargo/registry/src/github.com-1ecc6299db9ec823/rlibc-1.0.0/src/lib.rs --crate-type lib --emit=dep-info,link -C panic=abort -C debuginfo=2 -C metadata=0c8f9a9e32ead1fa -C extra-filename=-0c8f9a9e32ead1fa --out-dir /$project/demo/target/aarch64-none-elf/debug/deps --target aarch64-none-elf -L dependency=/$project/demo/target/aarch64-none-elf/debug/deps -L dependency=/$project/demo/target/debug/deps --cap-lints warn --sysroot $home/.xargo`
   Compiling demo v0.1.0 (file:///$project/demo)
     Running `rustc --crate-name demo src/lib.rs --crate-type staticlib --emit=dep-info,link -C panic=abort -C lto -C debuginfo=2 -C metadata=f64bb00341a09168 -C extra-filename=-f64bb00341a09168 --out-dir /$project/demo/target/aarch64-none-elf/debug/deps --target aarch64-none-elf -L dependency=/$project/demo/target/aarch64-none-elf/debug/deps -L dependency=/$project/demo/target/debug/deps --extern rlibc=/$project/demo/target/aarch64-none-elf/debug/deps/librlibc-0c8f9a9e32ead1fa.rlib --sysroot $home/.xargo`
    Finished dev [unoptimized + debuginfo] target(s) in 0.88 secs
```

I've tried `xargo clean`, `rm -rf ~/.xargo`, wiping and reinstalling the latest nightly releases, and wiping and reinstalling `xargo`, to no avail.

From the looks of the logs, this looks like it might be either a bug in `cargo`/`rustc` or a change in the way that `cargo`/`rustc` finds custom target files.

### PR DESCRIPTION
**Pull request by japaric**
to let rustc find custom target specification files located in the current directory

closes #186

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f5349aa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f5349aa3fca776546b64407fc4be59f041c53e2a with merge 71cb96b4946ec92300b5bade4bd8681e3064bbde...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.205), [status-travis](https://travis-ci.org/japaric/xargo/builds/322329289?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 71cb96b4946ec92300b5bade4bd8681e3064bbde to master...

**Pull request merged**
