### PR TITLE
allow relative paths in dependencies.{}.path

### LINKED ISSUE #120: Allow relative path dependencies in Xargo.toml
For example, I would like it if this were able to work:
```
[dependencies.std]
path = "../ctr-std"
stage = 2
```

### PR DESCRIPTION
**Pull request by japaric**
closes #120

cc @FenrirWolf

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1cf9bc2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1cf9bc2 with merge 1cf9bc2...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.174), [status-travis](https://travis-ci.org/japaric/xargo/builds/193773931)
Approved by: japaric
Pushing 1cf9bc27fc9cd467f129aacd42480d5eb9c5d0e5 to master...

**Pull request merged**
