### PR TITLE
Revert "use Cargo.lock file from rust-src if present"

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 192bbc2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 192bbc2858ae180609bd681ae202c1a8d78af1b2 with merge 64c727547f8d7bb614836438fe87d26460ad286b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.206)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3533108 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3533108e149e94564664ce37438ccf59691f6074 with merge 191ca4d65c2532bf984b5ba25d995ec05d833314...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.207)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 682cdbe has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 682cdbe05cfc0ca4dba43511a87643cafc068edd with merge 4289077adb188ca96044bc0f04dec8340c2c25b9...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e4d493f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e4d493fdc4e192f3a98f0381a674754880e3561e with merge aca707144960710e5050551f958f5fd1acefa726...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.209), [status-travis](https://travis-ci.org/japaric/xargo/builds/322388328?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing aca707144960710e5050551f958f5fd1acefa726 to master...

**Comment by RalfJung** [comment]
Hm, is there any discussion anywhere of why this revert happened?

As a matter of principle, using the lockfile seems to make much more sense for the reasons laid out in https://github.com/rust-lang/wg-cargo-std-aware/issues/12: it is the only way that we can reliably build old versions of libstd. And also practically speaking, every now and then an update lands on crates.io that is not forwards-compatible enough to keep libstd working -- it might add a warning (and we build with `deny(warnings)`), or it might [circumvent our patch section](https://github.com/SimonSapin/rust-typed-arena/pull/30#issuecomment-529637212). Applying the lockfile is crucial to avoid such issues.

**Pull request merged**
