### PR TITLE
build a sysroot when compiling natively

### LINKED ISSUE #106: Build modified versoin of std
I'm working on std (in `~/dev/rust/rust`), with a test crate in `/tmp/test`. I tried exporting `XARGO_RUST_SRC` and running `xargo build`, but it only build the test crate and not the modified `std`. How can I do that?

### PR DESCRIPTION
**Pull request by japaric**
closes #106

cc @Yamakaky

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ecb4cb8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ecb4cb8 with merge ecb4cb8...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/188662178)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c428cf1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c428cf1 with merge c428cf1...

**Comment by Yamakaky** [comment]
Cool!

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.164), [status-travis](https://travis-ci.org/japaric/xargo/builds/188682799)
Approved by: japaric
Pushing c428cf1f3096f6832f8f0fc8ef337fa73454934a to master...

**Pull request merged**
