### PR TITLE
don't trigger sysroot rebuilds on some commands

### LINKED ISSUE #49: `xargo clean` sometimes causes dependencies to be built
It seems that when I change rustc versions (with rustup), a `xargo clean` command will trigger the normal dependency generation process.

```bash
➜  teensy3-rs-demo git:(master) ✗ xargo clean
   Compiling sysroot for thumbv7em-none-eabi
   Compiling core v0.0.0 (file:///Users/jamesmunns/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore)
   Compiling rand v0.0.0 (file:///Users/jamesmunns/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/librand)
   Compiling alloc v0.0.0 (file:///Users/jamesmunns/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc)
   Compiling rustc_unicode v0.0.0 (file:///Users/jamesmunns/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/librustc_unicode)
   Compiling collections v0.0.0 (file:///Users/jamesmunns/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcollections)
    Finished release [optimized] target(s) in 17.72 secs
```

I would not expect a clean command to build anything

### PR DESCRIPTION
**Pull request by japaric**
like clean and update

closes #49

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 99343d2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 99343d2 with merge 99343d2...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.87)
Approved by: japaric
Pushing 99343d27ccc519bf51fdcbdc26101debc74ca4e7 to master...

**Pull request merged**
