### PR TITLE
print a warning when stable or beta is used

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c7794f3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c7794f3 with merge c7794f3...

**Comment by homunkulus** [comment]
:boom: Test timed out

**Comment by japaric** [comment]
Tests passed but homu didn't get the result, it seems. Merging manually.

**Pull request merged**
