### PR TITLE
Xargo.toml, support other built-in targets, refactor

### LINKED ISSUE #77: Cross compile std
For starters, with a few restrictions
- Xargo won't compile std for the host
- No custom std source
- The Cargo features of `std` can't be tweaked

These issues need to be addressed in rust-lang/rust:
- rust-lang/rust#37252
- rust-lang/rust#36501

But there are probably others. The easiest way to test this feature today is by compiling a binary Cargo project with the following Cargo.toml.

``` toml
[dependencies]
std = "$(rustc --print sysroot)/lib/rustlib/src/rust/src/libstd"
```

### LINKED ISSUE #98: Customization of std
Once #77 is implemented, people are going to ask for a way to customize the std crate (jemalloc vs alloc_system, backtrace or not, etc.).

So, I have been thinking about how to present "customizability" to users and how to solve the problem of nasty build errors, like libc, that are not actual errors.

My idea is to, by default, only build the `core` crate and have users specify what other dependencies they want + how to customize them via a Xargo.toml file in the root of the Cargo project.

Syntax is undecided but maybe something that looks like Cargo.toml:

``` toml
# Xargo.toml
[dependencies]
collections = "0"  # NOTE version doesn't actually matter

[dependencies.compiler-builtins]
features = ["mem"]
version = "0"
```

### PR DESCRIPTION
**Pull request by japaric**
closes #77
closes #98

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fb36b3b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fb36b3b with merge fb36b3b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/187252489)

**Comment by homunkulus** [comment]
:hourglass: Testing commit 60ec918 with merge 60ec918...

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 9a0a293 with merge 9a0a293...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/187286178)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 1352755 with merge 1352755...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/xargo/builds/187291851)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit f74fd90 with merge f74fd90...

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 2b65742 with merge 2b65742...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e9e7ec8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e9e7ec8 with merge e9e7ec8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.151), [status-travis](https://travis-ci.org/japaric/xargo/builds/187299145)
Approved by: japaric
Pushing e9e7ec82c2c45614fbf927cad29df245d79abfc7 to master...

**Pull request merged**
