### PR TITLE
update changelog, improve formatting of error messages

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2def6ea has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2def6ea with merge 2def6ea...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.122)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2def6ea with merge 2def6ea...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c7cb5e0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c7cb5e0 with merge c7cb5e0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.123), [status-travis](https://travis-ci.org/japaric/xargo/builds/169833828)
Approved by: japaric
Pushing c7cb5e0223ae12acca4d2fab98359514cc52c5ee to master...

**Pull request merged**
