### PR TITLE
support [dependencies] in Xargo.toml

### LINKED ISSUE #111: Support [dependencies] in Xargo.toml
These apply to all targets

### PR DESCRIPTION
**Pull request by japaric**
closes #111

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8cd4103 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8cd4103 with merge 8cd4103...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.165)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 53d9174 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 53d9174 with merge 53d9174...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 28a0571 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 28a0571 with merge 28a0571...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.167), [status-travis](https://travis-ci.org/japaric/xargo/builds/189940881)
Approved by: japaric
Pushing 28a05711bf89dd5f737ad661134976607c389ecd to master...

**Pull request merged**
