### PR TITLE
don't add a weird " ( )" to `xargo -V` if not building from a git repo

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3dcec73 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7f40ca9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7f40ca9 with merge 9c328c8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.120), [status-travis](https://travis-ci.org/japaric/xargo/builds/169336791)
Approved by: japaric
Pushing 9c328c8a0de33daecb15763c0ad57dcc5760ab95 to master...

**Pull request merged**
