### PR TITLE
add categories to Cargo.toml

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aca8c9a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aca8c9a with merge aca8c9a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.179), [status-travis](https://travis-ci.org/japaric/xargo/builds/226547484)
Approved by: japaric
Pushing aca8c9a6e8a2d9f41b5b20299042e0c13e37d092 to master...

**Pull request merged**
