### PR TITLE
build a sysroot for the new built-in thumb targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 66fe1d5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 66fe1d5 with merge 66fe1d5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/xargo/build/1.0.89)
Approved by: japaric
Pushing 66fe1d5d6614fec26f77e176916cb90d76212cf3 to master...

**Pull request merged**
